# ~/n8n-secrets.yaml
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: n8n-secrets
  namespace: default
  labels:
    app: n8n
    component: secrets
stringData:
  # Database password
  DB_POSTGRESDB_PASSWORD: "n8n" #changeme...
  # Basic auth credentials
  N8N_BASIC_AUTH_PASSWORD: "n8n" #changeme...
  # Encryption key to hash all data
  N8N_ENCRYPTION_KEY: "n8n" #changeme...
